modLoader = "javafml"
loaderVersion = "*"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "roughlyenoughconfigscreens"
version = "${version}"
displayName = "Roughly Enough Config Screens"
authors = "Jab125"
description = '''
Automatically creates config screens for mods that use either the Forge config system or the Framework config system.
Also supports JEI.
'''
logoFile="recs.png"

[[dependencies.roughlyenoughconfigscreens]]
modId = "forge"
mandatory = true
type="required"
versionRange = "$forge"
ordering = "NONE"
side = "BOTH"

[[dependencies.roughlyenoughconfigscreens]]
modId = "minecraft"
mandatory = true
type="required"
versionRange = "$minecraftVersion"
ordering = "NONE"
side = "BOTH"

[[dependencies.roughlyenoughconfigscreens]]
modId="jei"
mandatory = false
type="optional"
versionRange="$jeiDep"
ordering="NONE"
side="BOTH"

[[dependencies.roughlyenoughconfigscreens]]
modId="cloth_config"
mandatory=true
type="required"
versionRange="$clothConfigDep"
ordering="NONE"
side="BOTH"