modLoader = "javafml"
loaderVersion = "*"
license = "LGPL-2.1-only"

[[mods]]
modId = "re2"
version = "${version}"
displayName = "REI Integrations (RE2)"
authors = "Jab125"
description = '''
REI support for mods that don't provide REI support by default!
'''
logoFile="logo.png"
displayTest="IGNORE_ALL_VERSION" # doesn't matter if mod is installed on client or on server and vice versa.

[[dependencies.re2]]
modId = "forge"
mandatory = true
type="required"
versionRange = "$forge"
ordering = "NONE"
side = "BOTH"

[[dependencies.re2]]
modId = "minecraft"
mandatory = true
type="required"
versionRange = "$minecraftVersion"
ordering = "NONE"
side = "BOTH"

[[dependencies.re2]]
modId="roughlyenoughitems"
mandatory = true
type="required"
versionRange="$reiDep"
ordering="NONE"
side="BOTH"

[[dependencies.re2]]
modId="refurbished_furniture"
mandatory = true
type="required"
versionRange="$rfmDep"
ordering="NONE"
side="BOTH"

[[dependencies.re2]]
modId="cloth_config"
mandatory=true
type="required"
versionRange="$clothConfigDep"
ordering="NONE"
side="BOTH"

[modproperties.re2]
configuredBackground="minecraft:textures/block/cherry_planks.png"