modLoader = "javafml"
loaderVersion = "*"
license = "LGPL-2.1-only"

[[mods]]
modId = "reiintegration"
version = "${version}"
displayName = "REI Integration"
authors = "Jab125"
description = '''
REI support for mods that don't provide REI support by default!!
'''
logoFile="logo.png"
displayTest="IGNORE_ALL_VERSION" # doesn't matter if mod is installed on client or on server and vice versa.

[[dependencies.reiintegration]]
modId = "forge"
mandatory = true
type="required"
versionRange = "$forge"
ordering = "NONE"
side = "BOTH"

[[dependencies.reiintegration]]
modId = "minecraft"
mandatory = true
type="required"
versionRange = "$minecraftVersion"
ordering = "NONE"
side = "BOTH"

[[dependencies.reiintegration]]
modId="roughlyenoughitems"
mandatory = true
type="required"
versionRange="$reiDep"
ordering="NONE"
side="BOTH"

[[dependencies.reiintegration]]
modId="refurbished_furniture"
mandatory = true
type="required"
versionRange="$rfmDep"
ordering="NONE"
side="BOTH"

[[dependencies.reiintegration]]
modId="cloth_config"
mandatory=true
type="required"
versionRange="$clothConfigDep"
ordering="NONE"
side="BOTH"

[modproperties.reiintegration]
configuredBackground="minecraft:textures/block/stone.png"